{"uid":"1ba3aa668f567f18","name":"test_login","fullName":"test_login#test_login","historyId":"7a6d5049f9f16ad82653dde78c1774b6","time":{"start":1754476918067,"stop":1754476933173,"duration":15106},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":7,"retriesStatusChange":true,"beforeStages":[{"name":"appium_driver","time":{"start":1754476897027,"stop":1754476918046,"duration":21019},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"passed","steps":[],"attachments":[{"uid":"dc1d36baf38b42e0","name":"stdout","source":"dc1d36baf38b42e0.txt","type":"text/plain","size":19}],"parameters":[],"hasContent":true,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":1},"afterStages":[{"name":"appium_driver::0","time":{"start":1754476933175,"stop":1754476938264,"duration":5089},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentStep":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"labels":[{"name":"suite","value":"test_login"},{"name":"host","value":"PUMA-71500-WL"},{"name":"thread","value":"18436-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"9a5489c9cc755d91","status":"passed","time":{"start":1753859897793,"stop":1753859914808,"duration":17015}},{"uid":"862565fa0f7b5a6b","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@name='username']\"}\n  (Session info: chrome=133.0.6943.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7076B1805+3048677]\n\t(No symbol) [0x00007FF707333B20]\n\t(No symbol) [0x00007FF7071B8FBA]\n\t(No symbol) [0x00007FF70720F27A]\n\t(No symbol) [0x00007FF70720F4AC]\n\t(No symbol) [0x00007FF707262B87]\n\t(No symbol) [0x00007FF7072372CF]\n\t(No symbol) [0x00007FF70725F849]\n\t(No symbol) [0x00007FF707237063]\n\t(No symbol) [0x00007FF7071FFFC0]\n\t(No symbol) [0x00007FF707201273]\n\tGetHandleVerifier [0x00007FF707711F5D+3443773]\n\tGetHandleVerifier [0x00007FF70772596A+3524170]\n\tGetHandleVerifier [0x00007FF70771B1A3+3481219]\n\tGetHandleVerifier [0x00007FF70749A26A+855882]\n\t(No symbol) [0x00007FF70733EB3F]\n\t(No symbol) [0x00007FF70733AB64]\n\t(No symbol) [0x00007FF70733AD06]\n\t(No symbol) [0x00007FF707329E79]\n\tBaseThreadInitThunk [0x00007FF9E2BEE8D7+23]\n\tRtlUserThreadStart [0x00007FF9E3D9C34C+44]","time":{"start":1753859484494,"stop":1753859517459,"duration":32965}},{"uid":"e6e133826e029112","status":"passed","time":{"start":1753789486459,"stop":1753789503795,"duration":17336}},{"uid":"e443a38f25dd707b","status":"passed","time":{"start":1753783527835,"stop":1753783579711,"duration":51876}},{"uid":"42c75e807db151d1","status":"passed","time":{"start":1753708430977,"stop":1753708447955,"duration":16978}},{"uid":"e0b75bf0b866873d","status":"passed","time":{"start":1753708374988,"stop":1753708389779,"duration":14791}},{"uid":"2e78f365e5a568ae","status":"passed","time":{"start":1753708309805,"stop":1753708325191,"duration":15386}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":8,"unknown":0,"total":10},"items":[{"uid":"94f621fab700ea9f","reportUrl":"http://localhost:8080/job/POMPython/27/allure/#testresult/94f621fab700ea9f","status":"passed","time":{"start":1753859897793,"stop":1753859914808,"duration":17015}},{"uid":"5e2e60791413824d","reportUrl":"http://localhost:8080/job/POMPython/26/allure/#testresult/5e2e60791413824d","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@name='username']\"}\n  (Session info: chrome=133.0.6943.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7076B1805+3048677]\n\t(No symbol) [0x00007FF707333B20]\n\t(No symbol) [0x00007FF7071B8FBA]\n\t(No symbol) [0x00007FF70720F27A]\n\t(No symbol) [0x00007FF70720F4AC]\n\t(No symbol) [0x00007FF707262B87]\n\t(No symbol) [0x00007FF7072372CF]\n\t(No symbol) [0x00007FF70725F849]\n\t(No symbol) [0x00007FF707237063]\n\t(No symbol) [0x00007FF7071FFFC0]\n\t(No symbol) [0x00007FF707201273]\n\tGetHandleVerifier [0x00007FF707711F5D+3443773]\n\tGetHandleVerifier [0x00007FF70772596A+3524170]\n\tGetHandleVerifier [0x00007FF70771B1A3+3481219]\n\tGetHandleVerifier [0x00007FF70749A26A+855882]\n\t(No symbol) [0x00007FF70733EB3F]\n\t(No symbol) [0x00007FF70733AB64]\n\t(No symbol) [0x00007FF70733AD06]\n\t(No symbol) [0x00007FF707329E79]\n\tBaseThreadInitThunk [0x00007FF9E2BEE8D7+23]\n\tRtlUserThreadStart [0x00007FF9E3D9C34C+44]","time":{"start":1753859484494,"stop":1753859517459,"duration":32965}},{"uid":"363cd47f11331cd2","reportUrl":"http://localhost:8080/job/POMPython/25/allure/#testresult/363cd47f11331cd2","status":"passed","time":{"start":1753789486459,"stop":1753789503795,"duration":17336}},{"uid":"260c7097ffa991dc","reportUrl":"http://localhost:8080/job/POMPython/24/allure/#testresult/260c7097ffa991dc","status":"passed","time":{"start":1753783527835,"stop":1753783579711,"duration":51876}},{"uid":"589ce734a2f99948","reportUrl":"http://localhost:8080/job/POMPython/23/allure/#testresult/589ce734a2f99948","status":"passed","time":{"start":1753776760892,"stop":1753776784064,"duration":23172}},{"uid":"f32f5fe57e9cd21d","reportUrl":"http://localhost:8080/job/POMPython/22/allure/#testresult/f32f5fe57e9cd21d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 30000ms\n    at getResponseForW3CError (C:\\Users\\zine_s\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1143:9)\n    at asyncHandler (C:\\Users\\zine_s\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:487:57)","time":{"start":1753775158995,"stop":1753775158995,"duration":0}},{"uid":"89cbfe8551ce0cb2","reportUrl":"http://localhost:8080/job/POMPython/20/allure/#testresult/89cbfe8551ce0cb2","status":"passed","time":{"start":1753708430977,"stop":1753708447955,"duration":16978}},{"uid":"22048dfd156845ba","reportUrl":"http://localhost:8080/job/POMPython/19/allure/#testresult/22048dfd156845ba","status":"passed","time":{"start":1753708374988,"stop":1753708389779,"duration":14791}},{"uid":"43be9f41df73c52c","reportUrl":"http://localhost:8080/job/POMPython/18/allure/#testresult/43be9f41df73c52c","status":"passed","time":{"start":1753708309805,"stop":1753708325191,"duration":15386}}]},"tags":[]},"source":"1ba3aa668f567f18.json","parameterValues":[]}